// Generated by CoffeeScript 1.3.3
(function() {

  describe("Chaves", function() {
    return describe("By Default", function() {
      beforeEach(function() {
        loadFixtures('default-list.html');
        return this.list = $('ul').chaves();
      });
      it("adds jquery-chaves to target element's className", function() {
        return expect(this.list).toHaveClass('jquery-chaves');
      });
      return it("contains spec with an exception", function() {
        return expect(true).toBe(true);
      });
    });
  });

}).call(this);
