// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.extend({
    chaves: function(options) {
      var self;
      self = $.fn.chaves;
      options = $.extend({}, self.default_options, options);
      return $(this).each(function(i, el) {
        self.init(el, options);
        if (options.log) {
          return self.log(el);
        }
      });
    }
  });

  $.extend($.fn.chaves, {
    default_options: {
      className: 'jquery-chaves',
      enableUpDown: false,
      log: true
    },
    init: function(el, options) {
      return el.className = options.className;
    },
    log: function(msg) {
      return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
    }
  });

}).call(this);
